// GENERATED by scripts/generate-site-data.mjs — do not edit by hand.
// Rebuilt from ../content/*.md during prebuild/predev so the vintage
// front page always shows the latest Bloggy pipeline dispatches.
import type { Article } from '../types';

export const PIPELINE_ARTICLES: Article[] = [];

export const PIPELINE_LATEST_DATE: string = "";
