"""Review stage: the git-based human gate.

Drafts land in `content/drafts/<slug>.md`, get pushed as a branch, and open a
GitHub PR. You review/edit in GitHub (the workflow you already know), merge the
PR, and your Vercel hook auto-deploys the site from `content/`.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from ..net import post_json

REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def _git(root: Path, *args: str) -> str:
    out = subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True)
    if out.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} -> {out.stderr.strip()[:300]}")
    return out.stdout.strip()


def push_pr(cfg, doc: str, title: str, slug: str) -> dict:
    """Write content/drafts/<slug>.md -> branch -> PR. Returns result dict.

    No GITHUB_TOKEN/GIT_REPO configured -> skipped (drafts stay local only).
    A shell dry-run command block is printed so you can do it by hand.
    """
    if not (cfg.github_token and cfg.git_repo):
        print(f"  [review] skipped (set GITHUB_TOKEN + GIT_REPO) — manual alternative:\n"
              f"           git checkout -b content/{slug} && git add content/drafts/{slug}.md && "
              f"git commit -m 'blog: draft {title[:40]}' && git push -u origin content/{slug}")
        return {"status": "skipped", "note": "GITHUB_TOKEN/GIT_REPO not set"}

    drafts = REPO_ROOT / "content" / "drafts"
    drafts.mkdir(parents=True, exist_ok=True)
    path = drafts / f"{slug}.md"
    path.write_text(doc)

    branch = f"content/{slug}"
    try:
        _git(REPO_ROOT, "checkout", "-b", branch)
    except RuntimeError:
        _git(REPO_ROOT, "checkout", branch)  # branch already exists
    _git(REPO_ROOT, "add", f"content/drafts/{slug}.md")
    _git(REPO_ROOT, "commit", "-m", f"blog: draft {title[:60]}")
    _git(REPO_ROOT, "push", "-u", "origin", branch)

    pr = post_json(
        f"https://api.github.com/repos/{cfg.git_repo}/pulls",
        {
            "title": f"Draft: {title[:60]}",
            "head": branch,
            "base": cfg.git_branch,
            "body": "Auto-generated by the Bloggy pipeline.\n\n- Source: see frontmatter\n- Checks: see Supabase `posts.checks`\n\nReview, edit, merge → Vercel deploys.",
        },
        headers={"Authorization": f"Bearer {cfg.github_token}", "Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"},
    )
    return {
        "status": "pr-open",
        "branch": branch,
        "pr_url": pr.get("html_url") or pr.get("url", ""),
        "pr_number": pr.get("number"),
        "draft_path": str(path),
    }